### ISSUE TITLE
Nodeのバージョンを指定する

### ISSUE THREAD

**Issue by mirror-kt** [Growthers/enshita#75]
`.node-version` などを使用して、プロジェクトで使用するnodeのバージョンを指定したい。
`.node-version` であればvoltaやnvm、asdf等で対応できるはず

指定するバージョン: 16系の最新版？

**Comment by Yusuke4869** [comment]
現時点でのLTS `v16.17.0` を推奨でいいと思うのですがどうでしょう

**Comment by mirror-kt** [comment]
いいと思います
